name: Check code formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: ogeth-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Check formatting with black
        shell: bash -l {0}
        run: |
          python -m black --check -l 79 .
